# Generated by Django 5.0.6 on 2025-07-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlacesocial',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='enlaces/'),
        ),
    ]
