services:
  - type: web
    name: artesanias-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn artesanias.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: artesanias.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        value: una-clave-larga-y-segura
      - key: DEBUG
        value: False
