# Generated by Django 5.0.6 on 2025-07-11 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_filtro'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='filtro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.filtro'),
        ),
    ]
